#Hugo configuration
title = "asdf"
baseURL = "https:\/\/WWW.HAAH.COM"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "HAAH.COM"
